leapfrogai:
  securityContext:
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

  migration:
    imageTag: "###ZARF_CONST_IMAGE_VERSION###"
    namespace: "leapfrogai"
    serviceName: "supabase-supabase-db"
    servicePort: "5432"
