apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nameOverride }}-configmap"
  namespace: {{ default "leapfrogai" .Release.Namespace }}
  labels:
    leapfrogai: sparkle
data:
  models.toml: |
    [[models]]
        owned_by    = 'Defense Unicorns'
        backend     = '{{ include "chart.fullname" . }}:50051'
        type        = 'gRPC'
        name        = '{{ .Values.nameOverride }}'
