apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ default "leapfrogai" .Release.Namespace }}
  annotations:
    zarf.dev/connect-description: "{{ .Values.nameOverride }} gRPC endpoint."
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    zarf.dev/connect-name: "{{ .Values.nameOverride }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
