package:
  create:
    set:
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/repeater"
      # x-release-please-start-version
      image_version: 0.9.0
      # x-release-please-end
      name: repeater
    max_package_size: "1000000000"
  deploy:
    set:
      limits_cpu: 1
      limits_memory: 4Gi
      limits_gpu: 0
      requests_cpu: 1
      requests_memory: 4Gi
      requests_gpu: 0
